text_missing/LoginApp/urls.py
from django.conf.urls import url

from . import views

app_name = "LoginApp"
urlpatterns = [
    url(r'^$', views.main_page, name='main'),
    url(r'^login/', views.login_page, name='login'),
    url(r'^logout/', views.logout_page, name='logout'),
    url(r'^change-account/', views.change_account, name='change_account')
]

text_missing/TextMissing/urls.py
from django.conf.urls import url
from django.views.static import serve

from text_missing import settings
from . import views

app_name = "TextMissing"
urlpatterns = [
    url(r'^documents/$', views.documents_page, name='documents'),
    url(r'^documents/delete_document/(?P<document_id>.*)', views.delete_document, name='delete_document'),
    url(r'^documents/update/(?P<document_id>.*)', views.update_document, name='update_document'),
    url(r'^documents/view_versions/(?P<document_id>.*)', views.view_versions, name='view_versions'),
    url(r'^add_document/(?P<document_type>.*)$', views.add_document, name='upload'),
    url(r'^zones/$', views.zones, name='zones'),
    url(r'^zones/work_zone/$', views.work_zone, name='work_zone'),
    url(r'^zones/initiated_zone/$', views.initiate_zone, name='initiated_zone'),
    url(r'^zones/task_zone/$', views.task_zone, name='task_zone'),
    url(r'^zones/finished_zone/$', views.finished_zone, name='finished_zone'),
    url(r'^flows/$',views.flows_page,name="flows"),
    url(r'^add_flow/$', views.add_flow_page, name="add_flow"),
    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

text_missing/text_missing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.models import User, Group

admin.site.unregister(User)
admin.site.unregister(Group)
admin.AdminSite.site_title = "Document Admin"
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('LoginApp.urls')),
    url(r'^', include('TextMissing.urls'))
]

text_missing/LoginApp/models.py
from __future__ import unicode_literals
import string
import struct
from os import urandom
from random import shuffle

from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.contrib.auth.models import User, Group


class Client(models.Model):
    last_name = models.CharField(max_length=40)
    first_name = models.CharField(max_length=40)
    email = models.EmailField()
    user = models.ForeignKey(User, null=True)
    temp_pass = models.CharField(max_length=40)
    is_activated = models.BooleanField("Active", default=False)
    type = models.CharField(max_length=30)

    def _gen_user(self):
        u_name = (self.first_name[0] + self.last_name).lower()
        base = u_name
        count = 0
        while User.objects.filter(username=u_name).all().count():
            u_name = base + str(count)
            count += 1
        return u_name

    def _set_type(self, type):
        group, created = Group.objects.get_or_create(name=type)
        self.user.groups.add(group)
        self.type = type

    @staticmethod
    def _gen_pass():
        alphabet = list(string.ascii_letters + string.digits + "!@#$%^&*")
        shuffle(alphabet)
        rbytes = urandom(13)
        password = ""
        for el in rbytes:
            bval = struct.unpack('B', bytes([el]))[0]
            password += alphabet[bval % len(alphabet)]
        return password

    def _create_user(self):
        self.temp_pass = self._gen_pass()
        self.user = User.objects.create_user(username=self._gen_user(), password=self.temp_pass, email=self.email)

    def get_temp_pass(self):
        if self.is_activated:
            return ""
        else:
            return self.temp_pass

    def get_user(self):
        return self.user.get_username()

    get_user.short_description = "Username"
    get_temp_pass.short_description = "Temporary password"

    def __str__(self):
        return self.last_name + " " + self.first_name


class Staff(Client):
    class Meta:
        verbose_name_plural = 'Staff'

    def save(self, *args, **kwargs):
        if not self.pk:
            self._create_user()
            self._set_type("staff")
            self.user.is_staff = True
            self.user.save()
            self.user.is_admin = True
            self.user.save()
            self.user.is_superuser = True
            self.user.save()
        super(Staff, self).save(*args, **kwargs)


class Contributor(Client):
    def save(self, *args, **kwargs):
        if not self.pk:
            self._create_user()
            self._set_type("contributor")
        super(Contributor, self).save(*args, **kwargs)


class Manager(Client):
    def save(self, *args, **kwargs):
        if not self.pk:
            self._create_user()
            self._set_type("manager")
        super(Manager, self).save(*args, **kwargs)


class Reader(Client):
    def save(self, *args, **kwargs):
        if not self.pk:
            self._create_user()
            self._set_type("reader")
        super(Reader, self).save(*args, **kwargs)


# SIGNALS start here
# Global flag to avoid infinite recursion
is_in_pre_delete = False


@receiver(pre_delete, sender=Client)
def pre_delete_client(sender, **kwargs):
    global is_in_pre_delete
    if is_in_pre_delete:
        return
    if not isinstance(kwargs["instance"], Client):
        return
    is_in_pre_delete = True
    user = kwargs["instance"].user
    kwargs["instance"].user = None
    user.delete()
    is_in_pre_delete = False


class GroupType(models.Model):
    name = models.CharField(max_length=64)

    def type_name(self):
        return self.name

    def user_groups(self):
        return "; ".join([u.name for u in self.groups.all()])

    def get_groups(self):
        return self.groups

    def __str__(self):
        return self.type_name()


class UserGroup(models.Model):
    name = models.CharField(max_length=64)
    leader = models.ForeignKey(Client, null=False, default=1, related_name="Leader")
    users = models.ManyToManyField(Client, related_name="Users")
    type = models.ForeignKey(GroupType, null=True, related_name="groups")

    def get_usergroup(self):
        return self.name

    def get_leader(self):
        return self.leader

    def get_users(self):
        return "\n".join([u.first_name+" "+u.last_name+"; " for u in self.users.all()])

text_missing/LoginApp/forms.py
from django.contrib.auth.forms import PasswordChangeForm
from django.core.exceptions import ValidationError
from django.forms import Form, CharField, PasswordInput
from django.contrib.auth.models import User


class LoginForm(Form):
    username = CharField(label="Username:", max_length=30)
    password = CharField(label="Password:", widget=PasswordInput())


class CustomizeAccountForm(PasswordChangeForm):
    username = CharField(label="Username:", max_length=30)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(PasswordChangeForm, self).__init__(user, *args, **kwargs)

    def clean_username(self):
        newusername = self.cleaned_data['username']
        if newusername == self.user.username:
            return newusername

        if User.objects.filter(username=newusername).exists():
            raise ValidationError("Username already exists!", code="user_already_exists")

        return newusername

    def save(self, commit=True):
        super(PasswordChangeForm, self).save(commit)
        self.user.username = self.cleaned_data.get("username")
        self.user.save()

text_missing/LoginApp/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.forms import ValidationError

from LoginApp.forms import LoginForm, CustomizeAccountForm


@login_required(login_url=reverse_lazy('LoginApp:login'))
def main_page(request):
    if request.user.is_staff:
        return redirect('admin:index')
    return render(request, "LoginApp/main_page.html", {'role': request.user.groups.first, "has_permission": True})


def login_page(request):
    new_form = LoginForm()
    if request.method != 'POST':
        return render(request, "LoginApp/login.html", {'form': new_form})
    auth_form = LoginForm(data=request.POST)
    if auth_form.is_valid():
        username = auth_form.cleaned_data["username"]
        password = auth_form.cleaned_data["password"]
        user = authenticate(username=username, password=password)
        if not user:
            auth_form.add_error(None, ValidationError("User or password wrong!"))
            return render(request, "LoginApp/login.html", {'form': auth_form})

        login(request, user)
        if "next" not in request.GET:
            return redirect("LoginApp:main")
        else:
            return HttpResponseRedirect(request.GET["next"])
    else:
        return render(request, "LoginApp/login.html", {'form': auth_form})


@login_required(login_url=reverse_lazy('LoginApp:login'))
def logout_page(request):
    logout(request)
    return render(request, "LoginApp/logout.html", {"title": "Logged out!"})


@login_required(login_url=reverse_lazy('LoginApp:login'))
def change_account(request):
    if request.method != 'POST':
        newForm = CustomizeAccountForm(user=request.user)
        newForm.fields["username"].initial = request.user.username;
        return render(request, "LoginApp/change_account.html", {'form': newForm})

    form = CustomizeAccountForm(user=request.user, data=request.POST)
    if form.is_valid():
        form.save()
        update_session_auth_hash(request, form.user)
        if not form.user.client_set.first().is_activated:
            obj = form.user.client_set.first()
            obj.is_activated = True
            obj.save()
        return render(request, "LoginApp/done_change_account.html", {'title': "Account updated!"})
    else:
        return render(request, "LoginApp/change_account.html", {'form': form})

text_missing/LoginApp/templates/LoginApp/base.html
{% load i18n admin_static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
{% load static %}
<link rel="stylesheet" type="text/css" href={% static "TextMissing/document.css" %}>
<link rel="stylesheet" type="text/css" href={% static "TextMissing/flows.css" %}>
<link rel="stylesheet" type="text/css" href="{% static "bootstrap/css/bootstrap.min.css" %}" />
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'LoginApp:change_account' %}">{% trans 'Customize account' %}</a> /
                {% endif %}
                <a href="{% url 'LoginApp:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->
    <script type="application/javascript" src="{% static "jquery/jquery-3.1.1.min.js" %}"></script>
    <script type="application/javascript" src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
</body>
</html>

text_missing/LoginApp/templates/LoginApp/base_site.html
{% extends "LoginApp/base.html" %}
{% load i18n admin_static %}
{% load staticfiles %}
{% block title %}{{ site_title }}{% endblock %}

{% block branding %}
    <h1 id="site-name"><a href={{ main_url }}>{{ site_title }}</a></h1>
{% endblock %}

{% block nav-global %}
    {% if has_permission %}
        <a class="header-link" href="{% url "TextMissing:documents" %}">Documents</a>
        <a class="header-link" href="{% url "TextMissing:zones" %}">Zones</a>
        <a class="header-link" href="{% url "TextMissing:flows" %}">Flows</a>
    {% endif %}
{% endblock %}

text_missing/LoginApp/templates/LoginApp/change_account.html
{% extends "LoginApp/base_site.html" %}
{% load i18n admin_static %}
{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'LoginApp:main' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Account customization' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}<div id="content-main">

<form method="post">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}


<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<fieldset class="module aligned wide">

<div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
</div>

<div class="form-row">
    {{ form.old_password.errors }}
    {{ form.old_password.label_tag }} {{ form.old_password }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    {{ form.new_password1.label_tag }} {{ form.new_password1 }}
    {% if form.new_password1.help_text %}
    <p class="help">{{ form.new_password1.help_text|safe }}</p>
    {% endif %}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    {{ form.new_password2.label_tag }} {{ form.new_password2 }}
    {% if form.new_password2.help_text %}
    <p class="help">{{ form.new_password2.help_text|safe }}</p>
    {% endif %}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="{% trans 'Save changes' %}" class="default" />
</div>

<script type="text/javascript">document.getElementById("id_old_password").focus();</script>
</div>
</form></div>

{% endblock %}

text_missing/LoginApp/templates/LoginApp/done_change_account.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'LoginApp:main' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Account change' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
<p>{% trans 'Your account was updated.' %}</p>
{% endblock %}

text_missing/LoginApp/templates/LoginApp/login.html
{% extends "LoginApp/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}" />
{{ form.media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-global %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">

{% if user.is_authenticated %}
<p class="errornote">
{% blocktrans with username=request.user.get_username trimmed %}
    You are authenticated as {{ username }}, but are not authorized to
    access this page. Would you like to login to a different account?
{% endblocktrans %}
</p>
{% endif %}

<form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}" />
  </div>
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="{% trans 'Log in' %}" />
  </div>
</form>

<script type="text/javascript">
document.getElementById('id_username').focus()
</script>
</div>
{% endblock %}

text_missing/LoginApp/templates/LoginApp/logout.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="{% url 'LoginApp:main' %}">{% trans 'Home' %}</a></div>{% endblock %}

{% block content %}

<p>{% trans "May the force be with you!" %}</p>

<p><a href="{% url 'LoginApp:login' %}">{% trans 'Log in again' %}</a></p>

{% endblock %}

text_missing/LoginApp/templates/LoginApp/main_page.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'LoginApp:main' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Main page' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
<p>Your user role is {{ role }}.</p>
{% endblock %}