text_missing/LoginApp/urls.py
from django.conf.urls import url

from . import views

app_name = "LoginApp"
urlpatterns = [
    url(r'^$', views.main_page, name='main'),
    url(r'^login/', views.login_page, name='login'),
    url(r'^logout/', views.logout_page, name='logout'),
    url(r'^change-account/', views.change_account, name='change_account')
]

text_missing/TextMissing/urls.py
from django.conf.urls import url
from django.views.static import serve

from text_missing import settings
from . import views

app_name = "TextMissing"
urlpatterns = [
    url(r'^documents/$', views.documents_page, name='documents'),
    url(r'^documents/delete_document/(?P<document_id>.*)', views.delete_document, name='delete_document'),
    url(r'^documents/update/(?P<document_id>.*)', views.update_document, name='update_document'),
    url(r'^documents/view_versions/(?P<document_id>.*)', views.view_versions, name='view_versions'),
    url(r'^add_document/(?P<document_type>.*)$', views.add_document, name='upload'),
    url(r'^zones/$', views.zones, name='zones'),
    url(r'^zones/work_zone/$', views.work_zone, name='work_zone'),
    url(r'^zones/initiated_zone/$', views.initiate_zone, name='initiated_zone'),
    url(r'^zones/task_zone/$', views.task_zone, name='task_zone'),
    url(r'^zones/finished_zone/$', views.finished_zone, name='finished_zone'),
    url(r'^flows/$',views.flows_page,name="flows"),
    url(r'^add_flow/$', views.add_flow_page, name="add_flow"),
    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

text_missing/text_missing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.models import User, Group

admin.site.unregister(User)
admin.site.unregister(Group)
admin.AdminSite.site_title = "Document Admin"
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('LoginApp.urls')),
    url(r'^', include('TextMissing.urls'))
]

text_missing/TextMissing/models.py
import math
from django.db import models

# Create your models here.
from django_countries.fields import CountryField

from LoginApp.models import Client


class StatusChoices:
    DRAFT = "draft"
    FINAL = "final"
    FINAL_REVISED = "finalRevised"
    BLOCKED = "blocked"
    CHOICES = (
        (DRAFT, "Draft"),
        (FINAL, "Final"),
        (FINAL_REVISED, "Final revised"),
        (BLOCKED, "Blocked")
    )


class DocumentType:
    UPLOADED = 'uploaded'
    DR = 'rector disposition'
    RN = 'necessity request'
    CHOICES = (
        (UPLOADED, "Uploaded"),
        (DR, "Rector disposition"),
        (RN, "Necessity request")
    )


class TravelMean:
    AUTO = "auto"
    PLANE = "plane"
    BOAT = "boat"
    TRAIN = "train"
    CHOICES = (
        (AUTO, "Auto"),
        (PLANE, "Plane"),
        (BOAT, "Boat"),
        (TRAIN, "Train")
    )


class FlowType:
    RECTOR_DISPOSITION = 'rector disposition'
    NECESSITY_REQUEST = 'necessity request'
    CHOICES = (
        (RECTOR_DISPOSITION, 'Rector Disposition'),
        (NECESSITY_REQUEST, "Necessity Request"),
    )


class FinancingSource:
    NO_FINANCING = 'no financing'
    COLLEGE_BUDGET = 'college budget'
    UNIVERSITY_BUDGET = 'university budget'
    PROJECT_FINANCING = 'project/grant'
    COMBINED_FINANCING = 'combined'
    CHOICES = (
        (NO_FINANCING, "No financing"),
        (COLLEGE_BUDGET, "College budget"),
        (UNIVERSITY_BUDGET, "University budget"),
        (PROJECT_FINANCING, "Project/grant financing"),
        (COMBINED_FINANCING, "Combined financing")
    )


class DocumentFlow(models.Model):
    name = models.CharField(max_length=30)
    flow_type = models.CharField(max_length=30, choices=FlowType.CHOICES)
    initiator = models.ForeignKey(Client, null=False, default=0)
    creation_date = models.DateField(auto_now_add=True)
    state = models.PositiveIntegerField(default=0)

    def execute_flow(self, flow_function, *params):
        flow_function(self, *params)

    def documents_in_flow(self):
        return "\n".join([document.document_name + ", " for document in self.documents.all()])

    def get_documents(self):
        return self.documents.all()

    def __str__(self):
        return self.name + " by " + str(self.initiator)


class Document(models.Model):
    document_name = models.CharField(max_length=64)
    author = models.ForeignKey(Client, null=False, default=1)
    size = models.FloatField(default=0)
    version = models.CharField(max_length=64, default=0.1)
    creation_date = models.DateField(auto_now_add=True)
    last_update = models.DateField(auto_now=True)
    abstract = models.CharField(max_length=100)
    keywords = models.CharField(max_length=100)
    file = models.FileField(upload_to='documents/%Y%m%d', null=True, blank=True)
    status = models.CharField(max_length=20, choices=StatusChoices.CHOICES)
    type = models.CharField(max_length=20, choices=DocumentType.CHOICES, default=DocumentType.UPLOADED)
    flow = models.ForeignKey(DocumentFlow, related_name="documents", null=True, default=None)

    def get_file_url(self):
        if self.file:
            return '/media/' + str(self.file)

    def get_file_name(self):
        return str(self.file).split("/")[-1]

    def save(self, *args, **kwargs):
        if len(self.versions.all()) > 0:
            self.document_name = self.versions.last().document_name
            self.author = self.versions.last().author
            self.size = self.versions.last().size
            self.version = self.versions.last().version
            self.creation_date = self.versions.last().creation_date
            self.last_update = self.versions.last().last_update
            self.abstract = self.versions.last().abstract
            self.keywords = self.versions.last().keywords
            self.file = self.versions.last().file
        super(Document, self).save(*args, **kwargs)

class DocumentVersion(models.Model):
    document_name = models.CharField(max_length=64)
    author = models.ForeignKey(Client, null=False, default=1)
    size = models.FloatField(default=0)
    version = models.CharField(max_length=64, default=0.1)
    creation_date = models.DateField(auto_now_add=True)
    last_update = models.DateField(auto_now=True)
    abstract = models.CharField(max_length=100)
    keywords = models.CharField(max_length=100)
    file = models.FileField(upload_to='documents/%Y%m%d', null=True, blank=True)
    document = models.ForeignKey(Document, null=True, related_name="versions")

    def get_file_url(self):
        if self.file:
            return '/media/' + str(self.file)

    def get_file_name(self):
        return str(self.file).split("/")[-1]


class UploadedDocument(Document):
    def save(self, *args, **kwargs):
        self.type = DocumentType.UPLOADED
        super(UploadedDocument, self).save(*args, **kwargs)


class NecessityRequestDocument(Document):
    def save(self, *args, **kwargs):
        self.type = DocumentType.RN
        super(NecessityRequestDocument, self).save(*args, **kwargs)


class RectorDispositionDocument(Document):
    phone_number = models.CharField(max_length=10, default=None)
    country = CountryField(default=None)
    city = models.CharField(max_length=20, default=None)
    travel_mean = models.CharField(max_length=20, choices=TravelMean.CHOICES, default=TravelMean.AUTO)
    travel_purpose = models.CharField(max_length=500, default=None)
    sum = models.PositiveIntegerField(default=0)
    sum_motivation = models.CharField(max_length=500, default=None)
    financing_source = models.CharField(max_length=20, choices=FinancingSource.CHOICES,
                                        default=FinancingSource.NO_FINANCING)

    def save(self, *args, **kwargs):
        self.type = DocumentType.DR
        super(RectorDispositionDocument, self).save(*args, **kwargs)

text_missing/TextMissing/views.py
import os

from django.contrib.auth.decorators import login_required, user_passes_test
from django.forms import model_to_dict
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, render_to_response

# Create your views here.
from django.template import RequestContext
from django.urls import reverse
from django.urls import reverse_lazy

from LoginApp.models import Client
from TextMissing.forms import AddDocumentForm, RectorDispositionForm, NecessityRequestForm, UpdateRectorDisposition, \
    UpdateNecessityRequest, AddFlowForm
from TextMissing.forms import AddDocumentForm, UpdateDocumentForm
from TextMissing.models import Document, DocumentType, RectorDispositionDocument, UploadedDocument, \
    NecessityRequestDocument, DocumentFlow
from TextMissing.utils.check_user import is_manager, is_contributor, is_manager_or_contributor
from TextMissing.utils.document_manager import DocumentManager
from text_missing import settings


@login_required(login_url=reverse_lazy('LoginApp:login'))
def documents_page(request):
    if request.user.is_staff:
        return redirect('admin:index')
    return render(request, "TextMissing/documents.html",
                  {'documents': Document.objects.all(), "document_types": DocumentType, "has_permission": True,
                   "is_manager_or_contributor": is_manager_or_contributor(request.user)})


@login_required(login_url=reverse_lazy('LoginApp:login'))
@user_passes_test(is_manager_or_contributor, login_url=reverse_lazy('LoginApp:login'))
def delete_document(request, document_id):
    print(request.method)
    if request.method == "GET":
        # files = Document.objects.filter(id=document_id)
        # os.remove(os.path.join(settings.MEDIA_ROOT, files.first().file.name))
        # files.delete()
        DocumentManager.remove_document(document_id)
    return redirect('TextMissing:documents')


@login_required(login_url=reverse_lazy('LoginApp:login'))
@user_passes_test(is_manager_or_contributor, login_url=reverse_lazy('LoginApp:login'))
def add_document(request, document_type):
    options = {
        DocumentType.UPLOADED: AddDocumentForm,
        DocumentType.DR: RectorDispositionForm,
        DocumentType.RN: NecessityRequestForm
    }
    return upload_form(request, options[document_type])


def update_form(request, document_id, update_form_class, document_class):
    current_user = Client.objects.filter(user=request.user).first()
    current_document = document_class.objects.filter(id=document_id).first()
    if request.method == 'POST':
        form = update_form_class(current_user, document_id, request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('TextMissing:documents')
    else:
        form = update_form_class(current_user, document_id, initial=model_to_dict(current_document))
    return render(request, 'TextMissing/upload_document.html', {'form': form, "has_permission": True})


@user_passes_test(is_manager_or_contributor, login_url=reverse_lazy('LoginApp:login'))
def update_document(request, document_id):
    options = {
        DocumentType.UPLOADED: UpdateDocumentForm,
        DocumentType.DR: UpdateRectorDisposition,
        DocumentType.RN: UpdateNecessityRequest
    }
    options_doc_type = {
        DocumentType.UPLOADED: UploadedDocument,
        DocumentType.DR: RectorDispositionDocument,
        DocumentType.RN: NecessityRequestDocument
    }
    document_type = Document.objects.filter(id=document_id).first().type
    return update_form(request, document_id, options[document_type], options_doc_type[document_type])


@login_required(login_url=reverse_lazy('LoginApp:login'))
def upload_form(request, document_form_class):
    current_user = Client.objects.filter(user=request.user).first()
    if request.method == 'POST':
        form = document_form_class(current_user, request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('TextMissing:documents')
    else:
        form = document_form_class(user=current_user)
    return render(request, 'TextMissing/upload_document.html', {'form': form, "has_permission": True})


@login_required(login_url=reverse_lazy('LoginApp:login'))
def zones(request):
    return render(request, 'TextMissing/zones.html',
                  {'documents': Document.objects.all(), "document_types": DocumentType, "has_permission": True,
                   "is_manager_or_contributor": is_manager_or_contributor(request.user)})

@login_required(login_url=reverse_lazy('LoginApp:login'))
def work_zone(request):
    files = Document.objects.all()
    current_user = Client.objects.filter(user=request.user).first()
    documents = []
    if request.method == 'GET':
        for file in files:
            if file.status == 'draft':
                if current_user.type == 'manager':
                    documents.append(file)
                elif file.author == current_user:
                    documents.append(file)
        return render(request, "TextMissing/work_zone.html",
                      {'documents': documents, "has_permission": True})


@login_required(login_url=reverse_lazy('LoginApp:login'))
def initiate_zone(request):
    files = Document.objects.all()
    current_user = Client.objects.filter(user=request.user).first()
    documents = []
    if request.method == 'GET':
        for file in files:
            if file.status == 'final' or file.status == 'finalRevised':
                if file.author == current_user:
                    documents.append(file)
        return render(request, "TextMissing/initiate_zone.html",
                      {'documents': documents, "has_permission": True})


@login_required(login_url=reverse_lazy('LoginApp:login'))
def task_zone(request):
    files = Document.objects.all()
    current_user = Client.objects.filter(user=request.user).first()
    documents = []
    if request.method == 'GET':
        for file in files:
            if file.status == 'final' or file.status == 'finalRevised':
                if file.author != current_user:
                    documents.append(file)
        return render(request, "TextMissing/task_zone.html",
                      {'documents': documents, "has_permission": True})


@login_required(login_url=reverse_lazy('LoginApp:login'))
def finished_zone(request):
    files = Document.objects.all()
    documents = []
    if request.method == 'GET':
        for file in files:
            if file.status == 'blocked':
                documents.append(file)
        return render(request, "TextMissing/task_zone.html",
                  {'documents': documents, "has_permission": True})


@login_required(login_url=reverse_lazy('LoginApp:login'))
def view_versions(request, document_id):
    doc = Document.objects.filter(id=document_id).first()
    return render(request, "TextMissing/version_list.html",
                  {'documents': doc.versions.all(), "has_permission": True,
                   "is_manager_or_contributor": is_manager_or_contributor(request.user) })


@login_required(login_url=reverse_lazy('LoginApp:login'))
def flows_page(request):
    flows = DocumentFlow.objects.all()

    return render(request, "TextMissing/flows.html", {"flows": flows, "has_permission": True,"is_manager_or_contributor": is_manager_or_contributor(request.user)})


@login_required(login_url=reverse_lazy('LoginApp:login'))
def add_flow_page(request):
    current_user = Client.objects.filter(user=request.user).first()
    if request.method == 'POST':
        form = AddFlowForm(current_user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('TextMissing:flows')
    else:
        form = AddFlowForm(user=current_user)
    return render(request, 'TextMissing/add-flow.html', {'form': form, "has_permission": True})

text_missing/TextMissing/templates/TextMissing/add-flow.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br/>
        <label></label>
        <input type="submit" value="Add Flow">
    </form>
{% endblock %}

text_missing/TextMissing/templates/TextMissing/document.html
<div class="document-container">
    <div class="metadata-name">
        {% if document.status != "blocked" and is_manager_or_contributor %}
            <a href="{% url "TextMissing:delete_document" document_id=document.id %}">
                <span class="delete-button glyphicon glyphicon-remove pull-left"></span>
            </a>
            <a href="{% url "TextMissing:update_document" document_id=document.id %}">
                <span class="update-button glyphicon glyphicon-pencil pull-left"></span>
            </a>
            <a href="{% url "TextMissing:view_versions" document_id=document.id %}">
                <span class="update-button glyphicon glyphicon-eye-open pull-left"></span>
            </a>
        {% endif %}
        <span>{{ document.document_name }}</span>
    </div>
    <div class="metadata-container">
        <div class="metadata-title">
            <div>Version</div>
            <div>Author</div>
            <div>Created on</div>
            <div>Last Updated</div>
            <div>Abstract</div>
            <div>File</div>
            <div>Size</div>
        </div>
        <div class="metadata-content">
            <div>{{ document.version }}</div>
            <div>{{ document.author }}</div>
            <div>{{ document.creation_date }}</div>
            <div>{{ document.last_update }}</div>
            <div>{{ document.abstract }}</div>
            <div><a href={{ document.get_file_url }}> {{ document.get_file_name }} </a></div>
            <div>{{ document.size|floatformat:2 }} MB</div>
        </div>
    </div>
</div>

text_missing/TextMissing/templates/TextMissing/document_version.html
{% load static %}
<link rel="stylesheet" type="text/css" href={% static "TextMissing/document.css" %}>

<div class="document-container">
    <div class="metadata-container">
        <div class="metadata-title">
            <div>Name</div>
            <div>Version</div>
            <div>Author</div>
            <div>Created on</div>
            <div>Last Updated</div>
            <div>Abstract</div>
            <div>File</div>
            <div>Size</div>
        </div>
        <div class="metadata-content">
            <div>{{ document.document_name }}</div>
            <div>{{ document.version }}</div>
            <div>{{ document.author }}</div>
            <div>{{ document.creation_date   }}</div>
            <div>{{ document.last_update }}</div>
            <div>{{ document.abstract }}</div>
            <div><a href={{ document.get_file_url }}> {{ document.get_file_name }} </a></div>
            <div>{{ document.size|floatformat:2 }} MB</div>
        </div>
    </div>
</div>

text_missing/TextMissing/templates/TextMissing/documents.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
        {% if is_manager_or_contributor %}
        <a href="{% url "TextMissing:upload" document_type=document_types.UPLOADED %}">
            <button class="generic-button">Upload document</button>
        </a>
        <a href="{% url "TextMissing:upload" document_type=document_types.DR %}">
            <button class="generic-button">Dispozitia Rectorului</button>
        </a>
        <a href="{% url "TextMissing:upload" document_type=document_types.RN %}">
            <button class="generic-button">Referat de necesitate</button>
        </a>
        {% endif %}
    <div style="display: flex; flex-direction: column">
        {% for doc in documents %}
            {% include "TextMissing/document.html" with document=doc %}
        {% endfor %}
    </div>
{% endblock %}

text_missing/TextMissing/templates/TextMissing/finished_zone.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}
{% block content %}
    <div class="text-center" style="font-size: 20px">Finished Tasks Zone</div>
    {% for doc in documents %}
            {% include "TextMissing/document.html" with document=doc %}
        {% endfor %}
{% endblock %}

text_missing/TextMissing/templates/TextMissing/flows.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
    {% if is_manager_or_contributor %}
    <a href="{% url "TextMissing:add_flow" %}">
        <button class="generic-button">Add Flow</button>
    </a>
    {% endif %}
    {% for flow in flows %}
        <div class="flow">
            <h2 style="margin:0;">{{ flow.name }}</h2>
            <h3 style="margin:0;">{{ flow.flow_type }}</h3>
            {% for document in flow.get_documents %}
                <div>
                    <a href={{ document.get_file_url }}> {{ document.get_file_name }} </a>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

text_missing/TextMissing/templates/TextMissing/initiate_zone.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}
{% block content %}
    <div class="text-center" style="font-size: 20px">Initiated Tasks Zone</div>
    {% for doc in documents %}
            {% include "TextMissing/document.html" with document=doc %}
        {% endfor %}
{% endblock %}

text_missing/TextMissing/templates/TextMissing/task_zone.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}
{% block content %}
    <div class="text-center" style="font-size: 20px">Tasks Zone</div>
    {% for doc in documents %}
            {% include "TextMissing/document.html" with document=doc %}
        {% endfor %}
{% endblock %}

text_missing/TextMissing/templates/TextMissing/upload_document.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
        <label></label>
        <input type="submit" value="Upload">
        </div>
    </form>
{% endblock %}

text_missing/TextMissing/templates/TextMissing/version_list.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
    <div style="display: flex; flex-direction: column">
        {% for doc in documents %}
            {% include "TextMissing/document_version.html" with document=doc %}
        {% endfor %}
    </div>
{% endblock %}

text_missing/TextMissing/templates/TextMissing/work_zone.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}
{% block content %}
    <div class="text-center" style="font-size: 20px">Work Zone</div>
    {% for doc in documents %}
            {% include "TextMissing/document.html" with document=doc %}
        {% endfor %}
{% endblock %}

text_missing/TextMissing/templates/TextMissing/zones.html
{% extends "LoginApp/base_site.html" %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
    <a href="{% url "TextMissing:work_zone" %}">
        <button class="generic-button">Work Zone</button>
    </a>
    {% if is_manager_or_contributor %}
        <a href="{% url "TextMissing:initiated_zone" %}">
        <button class="generic-button">Initiated Tasks Zone</button>
    </a>
    {% endif %}
    <a href="{% url "TextMissing:task_zone" %}">
        <button class="generic-button">Tasks Zone</button>
    </a>
    <a href="{% url "TextMissing:finished_zone" %}">
        <button class="generic-button">Finished Tasks Zone</button>
    </a>
{% endblock %}